[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
active-win-pos-rs = "0.9"
reqwest = { version = "0.12.24", features = ["json"] }
share = { path = "../share" }
fs2 = "0.4.3"
log = { workspace = true }
