[workspace]
members = [
    "client", "backend", "share",
]
resolver = "3"

[workspace.dependencies]
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
once_cell = "1.21.3"
